name: Deploy to Azure Web App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Configurar Git
        run: |
          git config --global user.email "github-actions@bot.com"
          git config --global user.name "GitHub Actions"
      - name: Hacer push a Azure con autenticación embebida
        env:
          AZURE_USERNAME: $webapp-proyecto-patrones-u2
          AZURE_PASSWORD: ${{ secrets.AZURE_DEPLOY_CREDENTIALS }}
        run: |
          REMOTE_URL="https://${AZURE_USERNAME}:${AZURE_PASSWORD}@webapp-proyecto-patrones-u2.scm.azurewebsites.net/webapp-proyecto-patrones-u2.git"
          git remote set-url origin "$REMOTE_URL"
          git push origin main:master --force
